---
title: Een afbeelding uit de bibliotheek kiezen
hero_image: images/banner.png
description: Een afbeelding uit de bibliotheek kiezen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Kies een afbeelding uit de bibliotheek
